[tool.poetry]
name = "bot-models"
version = "0.0.1"
description = "Shared models used for the Python codebase of Bloxlink."
authors = ["Bloxlink <oss@blox.link>"]
readme = "README.md"
homepage = "https://blox.link/"
repository = "https://github.com/bloxlink/bot-models"
packages = [{include = "bot_models"}]


[tool.poetry.dependencies]
python = "<3.13, >=3.12"
attrs = "^23.2.0"
hikari = {git = "https://github.com/hikari-py/hikari.git", rev = "refs/pull/1803/merge"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
